### ISSUE TITLE
Calendar for DB maintenance

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/cor-cm#39]
We'll need to discuss briefly how this would ideally be implemented. Possibilities:

1. Slack notifications
2. An Outlook calendar, either e.g. LTDS or separate

**Comment by kbowaterskelly** [comment]
This is a duplicate of #136

**Comment by kbowaterskelly** [comment]
1. What day of the month and time would we like to set for DB maintenance?
2. What format(s) would we like the calendar in? Slack, Outlook, etc.

**Comment by kbowaterskelly** [comment]
Flattened RDS production maintenance schedule to 08:00 UTC Monday, created an outlook calendar. Noting here a lot of pending maintenance on our DBs which may require further review.
